trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build-prod
  displayName: 'Install Dependencies & Build'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    output_location: 'dist'
    skip_app_build: true
    api_build_command: 'rm -rf ./node_modules'
    is_static_export: true
    azure_static_web_apps_api_token: $(STATIC_DEPLOY_TOKEN)
  displayName: Deploy to Azure Static Web App
